version: '3.4'

volumes:
    order_demo_mariadb:

services:
    php:
        build:
            context: ./.docker/php
            dockerfile: Dockerfile
        volumes:
            - ./:/app
            - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
            - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./.docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        environment:
            PHP_EXT_XDEBUG: debug,profile
            PHP_IDE_CONFIG: serverName=php-docker.local
        expose:
            - 9000
        working_dir: /app
        # command: sh -c 'php-fpm'
        command: tail -f /dev/null
        extra_hosts:
            - "host.docker.internal:host-gateway"

    # http://localhost:8000/
    nginx:
        build:
            context: ./.docker/nginx
            dockerfile: Dockerfile
        volumes:
            - ./:/app # serving of files in /public
            - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./.docker/nginx/mime.types:/etc/nginx/mime.types
        ports:
            - "8000:80"
            - "8001:81"
        depends_on:
            - php

    mariadb:
        image: mariadb:10.4.33
        environment:
            MARIADB_ROOT_PASSWORD: 'root_pass'
            MARIADB_USER: 'maria_user'
            MARIADB_PASSWORD: 'maria_pass'
            MARIADB_DATABASE: 'order_db'
        volumes:
            - order_demo_mariadb:/var/lib/mysql
        ports:
            - '3306:3306'
